account:
    path:     /
    defaults: { _controller: "WallishNopDebtBundle:Account:index" }

account_my:
    path:     /my
    defaults: { _controller: "WallishNopDebtBundle:Account:my" }

account_show:
    path:     /{id}/show
    defaults: { _controller: "WallishNopDebtBundle:Account:show" }

account_new:
    path:     /new
    defaults: { _controller: "WallishNopDebtBundle:Account:new" }

account_create:
    path:     /create
    defaults: { _controller: "WallishNopDebtBundle:Account:create" }
    methods:  POST

account_edit:
    path:     /{id}/edit
    defaults: { _controller: "WallishNopDebtBundle:Account:edit" }

account_update:
    path:     /{id}/update
    defaults: { _controller: "WallishNopDebtBundle:Account:update" }
    methods:  [POST, PUT]

account_delete:
    path:     /{id}/delete
    defaults: { _controller: "WallishNopDebtBundle:Account:delete" }
    methods:  [POST, DELETE]
