wallish_nop_debt_event:
    resource: "@WallishNopDebtBundle/Resources/config/routing/event.yml"
    prefix:   /event

wallish_nop_debt_pot:
    resource: "@WallishNopDebtBundle/Resources/config/routing/pot.yml"
    prefix:   /pot

wallish_nop_debt_type:
    resource: "@WallishNopDebtBundle/Resources/config/routing/type.yml"
    prefix:   /type

wallish_nop_debt_transaction:
    resource: "@WallishNopDebtBundle/Resources/config/routing/transaction.yml"
    prefix:   /transaction

wallish_nop_debt_account:
    resource: "@WallishNopDebtBundle/Resources/config/routing/account.yml"
    prefix:   /account

wallish_nop_debt_homepage:
    path:     /
    defaults: { _controller: WallishNopDebtBundle:Default:index }

